# Generated by Django 6.0.5 on 2026-05-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0002_video_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(default='processing'),
        ),
    ]
