# Generated by Django 6.0.7 on 2026-07-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0005_video_audio_url_captioned_video_url_subtitle_url_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='audio_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='captioned_video_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='subtitle_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
