# Generated by Django 6.0.7 on 2026-08-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0006_increase_url_lengths'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='srt_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
